version: '3.8'

services:
  # Migrations: Handle database migrations using a prebuilt image
  migrations:
    image: 025066273203.dkr.ecr.ap-southeast-2.amazonaws.com/olmate/cabuca-migrations:latest
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=/Data/CabUCADb.sqlite
      - ASPNETCORE_ENVIRONMENT=Production
      - DATA_PROTECTION_CERT_PATH=/certs/dp_keys.pfx
      - DATA_PROTECTION_CERT_PASSWORD=${DATA_PROTECTION_CERT_PASSWORD}
    volumes:
      - sqlite-data:/Data
      - ./certs/dp_keys.pfx:/certs/dp_keys.pfx:ro
      - data-protection-keys:/app/.aspnet/DataProtection-Keys
    env_file:
      - .env
    command: ["dotnet", "ef", "database", "update"]

  # API: Your ASP.NET Core application
  api:
    image: 025066273203.dkr.ecr.ap-southeast-2.amazonaws.com/olmate/cabuca-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/Data/CabUCADb.sqlite
    volumes:
      - sqlite-data:/Data
      - data-protection-keys:/app/.aspnet/DataProtection-Keys
      - ./certs/dp_keys.pfx:/certs/dp_keys.pfx:ro
    expose:
      - "8080"
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully

  # Nginx: Reverse proxy and SSL termination
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - api

  # Certbot: Obtain and renew Let's Encrypt certificates
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot

volumes:
  certbot-etc:
  certbot-www:
  sqlite-data:
  data-protection-keys:

